//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyecPOC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDPOC : DbContext
    {
        public BDPOC()
            : base("name=BDPOC")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<cuidad> cuidad { get; set; }
        public virtual DbSet<provincia> provincia { get; set; }
        public virtual DbSet<pymes> pymes { get; set; }
        public virtual DbSet<sub_categoria> sub_categoria { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
