//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyecPOC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int rut_pyme { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public int correo { get; set; }
        public int id_cuidad { get; set; }
        public int id_provincia { get; set; }
        public byte[] contraseña { get; set; }
        public int telefono { get; set; }
    
        public virtual cuidad cuidad { get; set; }
        public virtual provincia provincia { get; set; }
    }
}
